// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents an Incoterms DTO.
    /// </summary>
    public partial class PricingCalculatorApiContractsV1RequestsIncotermsDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsIncotermsDto class.
        /// </summary>
        public PricingCalculatorApiContractsV1RequestsIncotermsDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsIncotermsDto class.
        /// </summary>
        /// <param name="chargeNames">(Optional) Gets a collection of Charge
        /// Names to be used when a custom set of incoterms rules are being
        /// used.</param>
        public PricingCalculatorApiContractsV1RequestsIncotermsDto(int rule, IList<string> chargeNames = default(IList<string>))
        {
            Rule = rule;
            ChargeNames = chargeNames;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rule")]
        public int Rule { get; set; }

        /// <summary>
        /// Gets (Optional) Gets a collection of Charge Names to be used when a
        /// custom set of incoterms rules are being used.
        /// </summary>
        [JsonProperty(PropertyName = "chargeNames")]
        public IList<string> ChargeNames { get; private set; }

    }
}
