// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Representation of a ruleset.
    /// </summary>
    public partial class PricingCalculatorApiContractsV1RequestsRulesetDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsRulesetDto class.
        /// </summary>
        public PricingCalculatorApiContractsV1RequestsRulesetDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsRulesetDto class.
        /// </summary>
        /// <param name="deminimisBasePrices">(Required) The base charges for
        /// this definition.</param>
        /// <param name="chargeConfigurations">(Required) The charge
        /// configurations for charges based on a rate applied to the base
        /// charge amount.</param>
        /// <param name="sourceCountryIso">(Optional) The source country
        /// ISO.</param>
        /// <param name="declarationCountryIso">(Required) The declaration
        /// country ISO.</param>
        public PricingCalculatorApiContractsV1RequestsRulesetDto(IList<string> deminimisBasePrices, IList<PricingCalculatorApiContractsV1RequestsChargeConfigurationDto> chargeConfigurations, string sourceCountryIso = default(string), string declarationCountryIso = default(string))
        {
            SourceCountryIso = sourceCountryIso;
            DeclarationCountryIso = declarationCountryIso;
            DeminimisBasePrices = deminimisBasePrices;
            ChargeConfigurations = chargeConfigurations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets (Optional) The source country ISO.
        /// </summary>
        [JsonProperty(PropertyName = "sourceCountryIso")]
        public string SourceCountryIso { get; private set; }

        /// <summary>
        /// Gets (Required) The declaration country ISO.
        /// </summary>
        [JsonProperty(PropertyName = "declarationCountryIso")]
        public string DeclarationCountryIso { get; private set; }

        /// <summary>
        /// Gets or sets (Required) The base charges for this definition.
        /// </summary>
        [JsonProperty(PropertyName = "deminimisBasePrices")]
        public IList<string> DeminimisBasePrices { get; set; }

        /// <summary>
        /// Gets or sets (Required) The charge configurations for charges based
        /// on a rate applied to the base charge amount.
        /// </summary>
        [JsonProperty(PropertyName = "chargeConfigurations")]
        public IList<PricingCalculatorApiContractsV1RequestsChargeConfigurationDto> ChargeConfigurations { get; set; }

    }
}
