// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Monetary value DTO
    /// </summary>
    public partial class DeminimisDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DeminimisDto class.
        /// </summary>
        public DeminimisDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DeminimisDto class.
        /// </summary>
        /// <param name="applyWhenGreaterThanThresholdOnly">Specifies that the
        /// deminimis is applied only when the amount is greater, not when it
        /// is equal to the threshold.</param>
        public DeminimisDto(PriceDto threshold, bool applyWhenGreaterThanThresholdOnly)
        {
            Threshold = threshold;
            ApplyWhenGreaterThanThresholdOnly = applyWhenGreaterThanThresholdOnly;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "threshold")]
        public PriceDto Threshold { get; set; }

        /// <summary>
        /// Gets or sets specifies that the deminimis is applied only when the
        /// amount is greater, not when it is equal to the threshold.
        /// </summary>
        [JsonProperty(PropertyName = "applyWhenGreaterThanThresholdOnly")]
        public bool ApplyWhenGreaterThanThresholdOnly { get; set; }

    }
}
