// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Item DTO.
    /// </summary>
    public partial class PricingCalculatorApiContractsV1RequestsItemDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsItemDto class.
        /// </summary>
        public PricingCalculatorApiContractsV1RequestsItemDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsItemDto class.
        /// </summary>
        /// <param name="quantity">Gets items quantity.</param>
        /// <param name="vatRate">Gets Vat rate</param>
        /// <param name="dutyRate">Gets Duty rate</param>
        /// <param name="weight">Gets Weight</param>
        public PricingCalculatorApiContractsV1RequestsItemDto(PricingCalculatorApiContractsV1RequestsPriceDto inputPrice, PricingCalculatorApiContractsV1RequestsPriceDto inputDeliveryPrice, int? quantity = default(int?), double? vatRate = default(double?), double? dutyRate = default(double?), double? weight = default(double?))
        {
            Quantity = quantity;
            InputPrice = inputPrice;
            InputDeliveryPrice = inputDeliveryPrice;
            VatRate = vatRate;
            DutyRate = dutyRate;
            Weight = weight;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets items quantity.
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inputPrice")]
        public PricingCalculatorApiContractsV1RequestsPriceDto InputPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inputDeliveryPrice")]
        public PricingCalculatorApiContractsV1RequestsPriceDto InputDeliveryPrice { get; set; }

        /// <summary>
        /// Gets Vat rate
        /// </summary>
        [JsonProperty(PropertyName = "vatRate")]
        public double? VatRate { get; private set; }

        /// <summary>
        /// Gets Duty rate
        /// </summary>
        [JsonProperty(PropertyName = "dutyRate")]
        public double? DutyRate { get; private set; }

        /// <summary>
        /// Gets Weight
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public double? Weight { get; private set; }

    }
}
