// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Deminimis Response DTO.
    /// </summary>
    public partial class DeminimisResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DeminimisResponseDto class.
        /// </summary>
        public DeminimisResponseDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DeminimisResponseDto class.
        /// </summary>
        /// <param name="applyWhenGreaterThanThresholdOnly">Gets a value
        /// indicating whether [apply when greater than threshold
        /// only].</param>
        public DeminimisResponseDto(PriceResponseDto threshold = default(PriceResponseDto), bool? applyWhenGreaterThanThresholdOnly = default(bool?))
        {
            Threshold = threshold;
            ApplyWhenGreaterThanThresholdOnly = applyWhenGreaterThanThresholdOnly;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "threshold")]
        public PriceResponseDto Threshold { get; set; }

        /// <summary>
        /// Gets a value indicating whether [apply when greater than threshold
        /// only].
        /// </summary>
        [JsonProperty(PropertyName = "applyWhenGreaterThanThresholdOnly")]
        public bool? ApplyWhenGreaterThanThresholdOnly { get; private set; }

    }
}
