// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Monetary value DTO
    /// </summary>
    public partial class PricingCalculatorApiContractsV1ResponsesPriceResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1ResponsesPriceResponseDto class.
        /// </summary>
        public PricingCalculatorApiContractsV1ResponsesPriceResponseDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1ResponsesPriceResponseDto class.
        /// </summary>
        /// <param name="currencyIso">An ISO 4217 currency code string.</param>
        /// <param name="value">Monetary value</param>
        public PricingCalculatorApiContractsV1ResponsesPriceResponseDto(string currencyIso = default(string), double? value = default(double?))
        {
            CurrencyIso = currencyIso;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets an ISO 4217 currency code string.
        /// </summary>
        [JsonProperty(PropertyName = "currencyIso")]
        public string CurrencyIso { get; private set; }

        /// <summary>
        /// Gets monetary value
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double? Value { get; private set; }

    }
}
