// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Charge configuration response DTO
    /// </summary>
    public partial class PricingCalculatorApiContractsV1ResponsesChargeConfigurationResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1ResponsesChargeConfigurationResponseDto
        /// class.
        /// </summary>
        public PricingCalculatorApiContractsV1ResponsesChargeConfigurationResponseDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1ResponsesChargeConfigurationResponseDto
        /// class.
        /// </summary>
        /// <param name="name">Gets the name.</param>
        /// <param name="activeFrom">Gets the active from.</param>
        /// <param name="baseChargeNames">Gets the base charge names.</param>
        /// <param name="rate">Gets the rate.</param>
        public PricingCalculatorApiContractsV1ResponsesChargeConfigurationResponseDto(string name = default(string), int? chargeType = default(int?), System.DateTime? activeFrom = default(System.DateTime?), PricingCalculatorApiContractsV1ResponsesDeminimisResponseDto deminimis = default(PricingCalculatorApiContractsV1ResponsesDeminimisResponseDto), IList<string> baseChargeNames = default(IList<string>), double? rate = default(double?), PricingCalculatorApiContractsV1ResponsesPriceResponseDto minimumPayable = default(PricingCalculatorApiContractsV1ResponsesPriceResponseDto), PricingCalculatorApiContractsV1ResponsesPriceResponseDto minimumCollectible = default(PricingCalculatorApiContractsV1ResponsesPriceResponseDto), PricingCalculatorApiContractsV1ResponsesPriceResponseDto excess = default(PricingCalculatorApiContractsV1ResponsesPriceResponseDto), PricingCalculatorApiContractsV1ResponsesPriceResponseDto maximumPayable = default(PricingCalculatorApiContractsV1ResponsesPriceResponseDto), PricingCalculatorApiContractsV1ResponsesPriceResponseDto fixedChargeAmount = default(PricingCalculatorApiContractsV1ResponsesPriceResponseDto))
        {
            Name = name;
            ChargeType = chargeType;
            ActiveFrom = activeFrom;
            Deminimis = deminimis;
            BaseChargeNames = baseChargeNames;
            Rate = rate;
            MinimumPayable = minimumPayable;
            MinimumCollectible = minimumCollectible;
            Excess = excess;
            MaximumPayable = maximumPayable;
            FixedChargeAmount = fixedChargeAmount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the name.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chargeType")]
        public int? ChargeType { get; set; }

        /// <summary>
        /// Gets the active from.
        /// </summary>
        [JsonProperty(PropertyName = "activeFrom")]
        public System.DateTime? ActiveFrom { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deminimis")]
        public PricingCalculatorApiContractsV1ResponsesDeminimisResponseDto Deminimis { get; set; }

        /// <summary>
        /// Gets the base charge names.
        /// </summary>
        [JsonProperty(PropertyName = "baseChargeNames")]
        public IList<string> BaseChargeNames { get; private set; }

        /// <summary>
        /// Gets the rate.
        /// </summary>
        [JsonProperty(PropertyName = "rate")]
        public double? Rate { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimumPayable")]
        public PricingCalculatorApiContractsV1ResponsesPriceResponseDto MinimumPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimumCollectible")]
        public PricingCalculatorApiContractsV1ResponsesPriceResponseDto MinimumCollectible { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "excess")]
        public PricingCalculatorApiContractsV1ResponsesPriceResponseDto Excess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maximumPayable")]
        public PricingCalculatorApiContractsV1ResponsesPriceResponseDto MaximumPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fixedChargeAmount")]
        public PricingCalculatorApiContractsV1ResponsesPriceResponseDto FixedChargeAmount { get; set; }

    }
}
