// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pricing.Calculator.Web.App.ApiClients.CalculatorClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Representation of a ruleset.
    /// </summary>
    public partial class PricingCalculatorApiContractsV1RequestsChargeConfigurationDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsChargeConfigurationDto
        /// class.
        /// </summary>
        public PricingCalculatorApiContractsV1RequestsChargeConfigurationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PricingCalculatorApiContractsV1RequestsChargeConfigurationDto
        /// class.
        /// </summary>
        /// <param name="name">Name of the charge.</param>
        /// <param name="rate">Rate that the charge is applied on.</param>
        /// <param name="baseChargeNames">The base charges on which this charge
        /// is applied.</param>
        /// <param name="activeFrom">The date in which the charge is
        /// active.</param>
        public PricingCalculatorApiContractsV1RequestsChargeConfigurationDto(int chargeType, string name = default(string), PricingCalculatorApiContractsV1RequestsDeminimisDto deminimis = default(PricingCalculatorApiContractsV1RequestsDeminimisDto), double? rate = default(double?), IList<string> baseChargeNames = default(IList<string>), PricingCalculatorApiContractsV1RequestsPriceDto fixedChargeAmount = default(PricingCalculatorApiContractsV1RequestsPriceDto), System.DateTime? activeFrom = default(System.DateTime?), PricingCalculatorApiContractsV1RequestsPriceDto minimumPayable = default(PricingCalculatorApiContractsV1RequestsPriceDto), PricingCalculatorApiContractsV1RequestsPriceDto maximumPayable = default(PricingCalculatorApiContractsV1RequestsPriceDto), PricingCalculatorApiContractsV1RequestsPriceDto minimumCollectible = default(PricingCalculatorApiContractsV1RequestsPriceDto), PricingCalculatorApiContractsV1RequestsPriceDto excess = default(PricingCalculatorApiContractsV1RequestsPriceDto))
        {
            Name = name;
            Deminimis = deminimis;
            Rate = rate;
            ChargeType = chargeType;
            BaseChargeNames = baseChargeNames;
            FixedChargeAmount = fixedChargeAmount;
            ActiveFrom = activeFrom;
            MinimumPayable = minimumPayable;
            MaximumPayable = maximumPayable;
            MinimumCollectible = minimumCollectible;
            Excess = excess;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets name of the charge.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deminimis")]
        public PricingCalculatorApiContractsV1RequestsDeminimisDto Deminimis { get; set; }

        /// <summary>
        /// Gets rate that the charge is applied on.
        /// </summary>
        [JsonProperty(PropertyName = "rate")]
        public double? Rate { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chargeType")]
        public int ChargeType { get; set; }

        /// <summary>
        /// Gets the base charges on which this charge is applied.
        /// </summary>
        [JsonProperty(PropertyName = "baseChargeNames")]
        public IList<string> BaseChargeNames { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fixedChargeAmount")]
        public PricingCalculatorApiContractsV1RequestsPriceDto FixedChargeAmount { get; set; }

        /// <summary>
        /// Gets the date in which the charge is active.
        /// </summary>
        [JsonProperty(PropertyName = "activeFrom")]
        public System.DateTime? ActiveFrom { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimumPayable")]
        public PricingCalculatorApiContractsV1RequestsPriceDto MinimumPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maximumPayable")]
        public PricingCalculatorApiContractsV1RequestsPriceDto MaximumPayable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimumCollectible")]
        public PricingCalculatorApiContractsV1RequestsPriceDto MinimumCollectible { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "excess")]
        public PricingCalculatorApiContractsV1RequestsPriceDto Excess { get; set; }

    }
}
